version: '3'
services:
  pasca_api:
    image: node:18
    command: bash -c "npm install && npm run build && npm run serve"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "15126:3433"